shared:
  discord_client_id: <%= ENV['DISCORD_CLIENT_ID'] %>
  discord_client_secret: <%= ENV['DISCORD_CLIENT_SECRET'] %>
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
